name: firebase_flavors
description: A Dart CLI tool for configuring Firebase for multiple Flutter flavors.
version: 0.0.1
repository: https://github.com/andyhorn/firebase_flavors

environment:
  sdk: ^3.10.1

dependencies:
  args: ^2.7.0
  logger: ^2.4.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables: 
  firebase_flavors: firebase_flavors
